//
//  Constants.h
//  ngb-ipad
//
//  Created by Julian Król on 09/20/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//


FOUNDATION_EXPORT NSString const *API_BASE_LINK_REQUEST;
FOUNDATION_EXPORT NSString const *API_LOGIN;
FOUNDATION_EXPORT NSString const *API_PROFILES;
FOUNDATION_EXPORT NSString const *API_PROFILE;
FOUNDATION_EXPORT NSString const *API_SESSION;
FOUNDATION_EXPORT NSString const *API_NOTIFICATIONS;
FOUNDATION_EXPORT NSString const *API_CHANNELS;
FOUNDATION_EXPORT NSString const *API_GUIDE;
FOUNDATION_EXPORT NSString const *API_PROGRAMS;
FOUNDATION_EXPORT NSString const *API_ACTORS;
FOUNDATION_EXPORT NSString const *API_FRIENDS;
FOUNDATION_EXPORT NSString const *API_NUMENTRIES;
FOUNDATION_EXPORT NSString const *API_NUMENTRIES_VALUE;
FOUNDATION_EXPORT NSString const *API_IMAGES;
FOUNDATION_EXPORT NSString const *API_FORMAT_IMAGE;
FOUNDATION_EXPORT NSString const *API_IMAGES_SERVER;
FOUNDATION_EXPORT NSString const *API_START_TIME;
FOUNDATION_EXPORT NSString const *API_END_TIME;
FOUNDATION_EXPORT NSString const *API_SCHEDULE;

FOUNDATION_EXPORT NSString const *PASSWORD;
FOUNDATION_EXPORT NSString const *DATA_LOGIN;

FOUNDATION_EXPORT float const NOTIFICATIONS_TIME_INTERVAL;
FOUNDATION_EXPORT float const CHECKING_PROGRAM_TIME_INTERVAL;
FOUNDATION_EXPORT float const RELOAD_PROFILE_INFO;
FOUNDATION_EXPORT float const ACTOR_PICTURE_WIDTH;
FOUNDATION_EXPORT float const ACTOR_PICTURE_HEIGHT;

FOUNDATION_EXPORT float const NORMAL_SPEED_ANIMATION;

FOUNDATION_EXPORT NSString const *NOTIFICATION_SESSION_OBTAINED;
FOUNDATION_EXPORT NSString const *NOTIFICATION_HIDE_POSTER_LOADER;
FOUNDATION_EXPORT NSString const *NOTIFICATION_UPDATE_SCHEDULE;

